server:
  host: 127.0.0.1
  port: 5000
  secret_key: 'This string will be replaced with a proper key in production'

mysql:
  host: 127.0.0.1
  port: 3306
  user: 'root'
  passwd: '123'

qiniu:
  access_key: ''
  secret_key: ''
  buket_name: ''
  domin: ''

mail:
  host: 'smtp.exmail.qq.com'
  port: 25
  auth:
    user: ''
    passwd: ''

github:
  client_id: 'f7764bde15ab2962b374'
  client_secret: 'a36cf604ab6fc6fa23a1f50eba24d8b0d5edf62b'